apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: jenkins-k8s
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30050
